language: python
python:
  - 2.7
install: pip install -r requirements.txt
before_install:
  - fileid="19Ncjp89IWcIq1XuurFkGu2GZUU0Zzrna"
  - filename="test-data.tar.gz"
  - curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /dev/null
  - curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=${fileid}" -o ${filename}
  - tar -xzvf $filename
script:
#  toil-cwl-runner standard_bam_processing.cwl example_input.json
 - cwltool standard_bam_processing.cwl example_input.json
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rhshah
  password:
    secure: akKYA2qdto13uZyCO1RK4yZpQ0Ri+WLRFVpJLZjN5WDWTsjN3OB19wBS7eCmTj/KwA9MpuwzSeY2Ob9vYBIhXWXtMOFnxJ2ZZ+Usg8L6FtdygU20WJpkCg2aVgIhnC852IOXX/sHvntnUivNTcyRHF8/lZZhPwVKddB6k0lKp9fVcHwOBtOcAo1XEvmIqxucrkX3eXpGHRAJcIOFQ3zC9XINOJY+LGCOz51uYxZ5cz3kioA5Adi92ivYSgQBVywEm8CngarFzXRwQ2iVTMjA8zkhP+Y2HrdCjXR3yBPjwLrb1k+3+ko2q83FY0hiq7P09R3dGDVojCiuYN+elGW7tldqoYvYDXJ96kvtXF7BpraCBvFgireXPgmkx+tEMFDC5PL5v6JNmiFXpKkxoYmNybVyRxVBD5PGg/pmrZ1Zh9LKZ9QKBkNS4HoSPe8zaqw3bdYYu02U+CJ3mifBQlQkNE76ugR706Gbvbh1U3z7yYIiLv2tibr6bnYKbAERXBktLktvKmv0pY7OdF04gZSBomXCtMO2jrTiKZKtFcKpPQWbzm8B6XXtQsjz/j8OF3YVwUQGrhaMAlJHcIf4X2RCEpQZpHXACVsI3m7xtpLE1Ev1q/4ZP0QcULKkTbIcochcBirmzKLfyLSVWgKRXWLguKFV7uUWlpskloBH1HGHU/E=
  on:
    tags: true
    repo: msk-access/bam_collapsing
    python: 3.7