name: test_uncollapsed_bam_generation
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
jobs:
  test_uncollapsed_bam_generation:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 3
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        id: run-tox
        run: tox -vv
        env:
          PLATFORM: ${{ matrix.platform }}
