name: test_uncollapsed_bam_generation
on: [push, pull_request]
jobs:
  test_uncollapsed_bam_generation:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run Tox
        id: run-tox
        run: tox
